---@type BlackAtomCore.Config.ThemeDefinitionMap
local themes = {
    terra_spring_day = {
        order = 1,
        key = "terra_spring_day",
        label = "Terra Spring Day",
        icon = "󰧲  ",
        path = "black-atom-core.themes.spring_day",
        group = "seasons",
        status = "development",
        appearance = "light",
    },
    terra_spring_night = {
        order = 2,
        key = "terra_spring_night",
        label = "Terra Spring Night",
        icon = "󰧲 󰖔 ",
        path = "black-atom-core.themes.spring_night",
        group = "seasons",
        status = "release",
        appearance = "dark",
    },
    terra_summer_day = {
        order = 3,
        key = "terra_summer_day",
        label = "Terra Summer Day",
        icon = "󰂒  ",
        path = "black-atom-core.themes.summer_day",
        group = "seasons",
        status = "development",
        appearance = "light",
    },
    terra_summer_night = {
        order = 4,
        key = "terra_summer_night",
        label = "Terra Summer Night",
        icon = "󰂒 󰖔 ",
        path = "black-atom-core.themes.summer_night",
        group = "seasons",
        status = "release",
        appearance = "dark",
    },
    terra_fall_day = {
        order = 5,
        key = "terra_fall_day",
        label = "Terra Fall Day",
        icon = "  ",
        path = "black-atom-core.themes.fall_day",
        group = "seasons",
        status = "development",
        appearance = "light",
    },
    terra_fall_night = {
        order = 6,
        key = "terra_fall_night",
        label = "Terra Fall Night",
        icon = " 󰖔 ",
        path = "black-atom-core.themes.fall_night",
        group = "seasons",
        status = "release",
        appearance = "dark",
    },
    terra_winter_day = {
        order = 7,
        key = "terra_winter_day",
        label = "Terra Winter Day",
        icon = "  ",
        path = "black-atom-core.themes.winter_day",
        group = "seasons",
        status = "development",
        appearance = "light",
    },
    terra_winter_night = {
        order = 8,
        key = "terra_winter_night",
        label = "Terra Winter Night",
        icon = " 󰖔 ",
        path = "black-atom-core.themes.winter_night",
        group = "seasons",
        status = "release",
        appearance = "dark",
    },
}

return themes
