local M = {}

local CACHE_DIR_NAME = "black-atom"

---Returns the cache directory path, creating it if needed.
---@return string
function M.cache_dir()
    local dir = vim.fn.stdpath("data") .. "/" .. CACHE_DIR_NAME .. "/cache"
    vim.fn.mkdir(dir, "p")
    return dir
end

---Compute a hash of all highlight source file mtimes.
---Stats every .lua file under lua/black-atom/highlights/ recursively,
---sorted by path, and returns sha256 of the concatenated mtime strings.
---@return string
function M.compute_source_hash()
    local files_lib = require("black-atom.lib.files")
    local plugin_path = files_lib.get_plugin_path()
    local highlights_dir = files_lib.build_path(plugin_path, "lua", "black-atom", "highlights")
    local files = files_lib.scan_path_for_files(highlights_dir, nil)

    table.sort(files)

    local parts = {}
    for _, filepath in ipairs(files) do
        local stat = vim.uv.fs_stat(filepath)
        if stat then
            table.insert(parts, stat.mtime.sec .. "." .. stat.mtime.nsec)
        end
    end

    return vim.fn.sha256(table.concat(parts, ":"))
end

---Returns the deterministic cache file path for a given theme + config.
---Includes source hash so changes to highlight files auto-invalidate.
---@param theme_key string
---@param config BlackAtom.Config
---@return string
function M.path_for(theme_key, config)
    local config_hash = vim.fn.sha256(vim.inspect(config)):sub(1, 12)
    local source_hash = M.compute_source_hash():sub(1, 12)
    local filename = theme_key .. "_" .. config_hash .. "_" .. source_hash .. ".lua"
    return M.cache_dir() .. "/" .. filename
end

---Serialize a highlights map to a Lua source file that calls nvim_set_hl.
---@param path string
---@param highlights_map BlackAtom.Highlights
function M.write(path, highlights_map)
    local lines = {
        "-- Generated by black-atom. Do not edit manually.",
    }

    for group, def in pairs(highlights_map) do
        local args = {}

        if def.link then
            table.insert(args, string.format("link = %q", def.link))
        else
            if def.fg then
                table.insert(args, string.format("fg = %q", def.fg))
            end
            if def.bg then
                table.insert(args, string.format("bg = %q", def.bg))
            end
            if def.sp then
                table.insert(args, string.format("sp = %q", def.sp))
            end
            if def.blend then
                table.insert(args, string.format("blend = %d", def.blend))
            end

            for _, flag in ipairs({
                "bold",
                "italic",
                "underline",
                "undercurl",
                "underdouble",
                "underdashed",
                "underdotted",
                "strikethrough",
                "reverse",
                "standout",
            }) do
                if def[flag] then
                    table.insert(args, flag .. " = true")
                end
            end
        end

        table.insert(lines, string.format("vim.api.nvim_set_hl(0, %q, { %s })", group, table.concat(args, ", ")))
    end

    local content = table.concat(lines, "\n") .. "\n"

    local dir = vim.fn.fnamemodify(path, ":h")
    vim.fn.mkdir(dir, "p")

    local fd = assert(vim.uv.fs_open(path, "w", 420)) -- 0644
    vim.uv.fs_write(fd, content)
    vim.uv.fs_close(fd)
end

---Whether the highlight cache is disabled via the `BLACK_ATOM_NO_CACHE` env var.
---Any non-empty value disables the cache, except the literal strings "0" and
---"false" (case-insensitive) which are treated as enabled. Lets users bypass
---the cache during development without editing config: `BLACK_ATOM_NO_CACHE=1 nvim`.
---@return boolean
function M.is_disabled()
    local v = vim.env.BLACK_ATOM_NO_CACHE
    if not v or v == "" then
        return false
    end
    return v ~= "0" and v:lower() ~= "false"
end

---Delete all cache files in the cache directory.
function M.invalidate_all()
    local dir = M.cache_dir()
    local handle = vim.uv.fs_scandir(dir)
    if not handle then
        return
    end

    while true do
        local name, type = vim.uv.fs_scandir_next(handle)
        if not name then
            break
        end
        if type == "file" and name:match("%.lua$") then
            vim.uv.fs_unlink(dir .. "/" .. name)
        end
    end
end

return M
